# Generated by Django 3.2.3 on 2021-08-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegistrationModel',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField(unique=True)),
                ('salary', models.FloatField()),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
    ]
