# Generated by Django 3.2.3 on 2021-08-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forms1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregistrationmodel',
            name='dob',
            field=models.DateField(default='2001-01-01'),
        ),
    ]
