# Generated by Django 3.2.3 on 2021-08-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forms1', '0002_employeeregistrationmodel_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregistrationmodel',
            name='email',
            field=models.EmailField(default='xxxxxx@gmail.com', max_length=100),
        ),
    ]
