# Generated by Django 3.2.3 on 2021-08-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forms1', '0003_employeeregistrationmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
