# Generated by Django 3.2.3 on 2021-08-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='account_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
