# Generated by Django 3.2.3 on 2021-08-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact_no', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='student_images')),
                ('dob', models.DateField()),
                ('date_of_reg', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
