# Generated by Django 3.2.3 on 2021-07-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Contact', models.IntegerField(unique=True)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Otp', models.IntegerField(default=0)),
                ('Status', models.CharField(default='pending', max_length=30)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
