# Generated by Django 3.2.3 on 2021-07-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app15', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='course',
            field=models.ManyToManyField(to='app15.CourseModel'),
        ),
    ]
