# Generated by Django 3.2.3 on 2021-08-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetailsModel',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contact', models.IntegerField(unique=True)),
                ('photo', models.ImageField(upload_to='student_images')),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('date_of_reg', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
